### ISSUE TITLE
pip3 install fail

### ISSUE THREAD

**Issue by guenhael** [pantor/frankx#20]
Hello,

I have an issue at the last step when running the command : `pip3 install .`
Previously I used the command cmake with the option -DBUILD_TESTS=OFF (as I didn't installed catch2).
I don't know if this can be the reason why I got the following output:

```
~/frankx$ pip3 install .
Processing /home/user/frankx
Building wheels for collected packages: frankx
  Running setup.py bdist_wheel for frankx ... error
  Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-or0bn859/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /tmp/pip-wheel-yfenl37p --python-tag cp37:
  running bdist_wheel
  running build
  running build_py
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/frankx
  copying frankx/__init__.py -> build/lib.linux-x86_64-3.7/frankx
  copying frankx/gripper.py -> build/lib.linux-x86_64-3.7/frankx
  copying frankx/robot.py -> build/lib.linux-x86_64-3.7/frankx
  running build_ext
  CMake Error: The current CMakeCache.txt directory /tmp/pip-req-build-or0bn859/build/temp.linux-x86_64-3.7/CMakeCache.txt is different than the directory /home/user/frankx/build/temp.linux-x86_64-3.7 where CMakeCache.txt was created. This may result in binaries being created in the wrong place. If you are not sure, reedit the CMakeCache.txt
  CMake Error: The source "/tmp/pip-req-build-or0bn859/CMakeLists.txt" does not match the source "/home/user/frankx/CMakeLists.txt" used to generate cache.  Re-run cmake with a different source directory.
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-req-build-or0bn859/setup.py", line 91, in <module>
      zip_safe=False,
    File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3/dist-packages/wheel/bdist_wheel.py", line 188, in run
      self.run_command('build')
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
      self.run_command(cmd_name)
    File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
      self.distribution.run_command(command)
    File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/tmp/pip-req-build-or0bn859/setup.py", line 36, in run
      self.build_extension(ext)
    File "/tmp/pip-req-build-or0bn859/setup.py", line 65, in build_extension
      subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp)
    File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
      raise CalledProcessError(retcode, cmd)
  subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-or0bn859', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-or0bn859/build/lib.linux-x86_64-3.7/', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DEXAMPLE_VERSION_INFO=0.1.1', '-DCMAKE_BUILD_TYPE=Release', '-DUSE_PYTHON_EXTENSION=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE', '-DCMAKE_INSTALL_RPATH=$ORIGIN', '-DCMAKE_POSITION_INDEPENDENT_CODE=ON']' returned non-zero exit status 1.
  
  ----------------------------------------
  Failed building wheel for frankx
  Running setup.py clean for frankx
Failed to build frankx
Installing collected packages: frankx
  Running setup.py install for frankx ... error
    Complete output from command /usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-or0bn859/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8yf5jer6/install-record.txt --single-version-externally-managed --compile --user --prefix=:
    running install
    running build
    running build_py
    creating build/lib.linux-x86_64-3.7
    creating build/lib.linux-x86_64-3.7/frankx
    copying frankx/__init__.py -> build/lib.linux-x86_64-3.7/frankx
    copying frankx/gripper.py -> build/lib.linux-x86_64-3.7/frankx
    copying frankx/robot.py -> build/lib.linux-x86_64-3.7/frankx
    running build_ext
    -- The CXX compiler identification is GNU 8.3.0
    -- Check for working CXX compiler: /usr/bin/c++
    -- Check for working CXX compiler: /usr/bin/c++ -- works
    -- Detecting CXX compiler ABI info
    -- Detecting CXX compiler ABI info - done
    -- Detecting CXX compile features
    -- Detecting CXX compile features - done
    CMake Error at CMakeLists.txt:17 (find_package):
      By not providing "FindFranka.cmake" in CMAKE_MODULE_PATH this project has
      asked CMake to find a package configuration file provided by "Franka", but
      CMake did not find one.
    
      Could not find a package configuration file provided by "Franka" (requested
      version 0.7) with any of the following names:
    
        FrankaConfig.cmake
        franka-config.cmake
    
      Add the installation prefix of "Franka" to CMAKE_PREFIX_PATH or set
      "Franka_DIR" to a directory containing one of the above files.  If "Franka"
      provides a separate development package or SDK, be sure it has been
      installed.
    
    
    -- Configuring incomplete, errors occurred!
    See also "/tmp/pip-req-build-or0bn859/build/temp.linux-x86_64-3.7/CMakeFiles/CMakeOutput.log".
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/tmp/pip-req-build-or0bn859/setup.py", line 91, in <module>
        zip_safe=False,
      File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 145, in setup
        return distutils.core.setup(**attrs)
      File "/usr/lib/python3.7/distutils/core.py", line 148, in setup
        dist.run_commands()
      File "/usr/lib/python3.7/distutils/dist.py", line 966, in run_commands
        self.run_command(cmd)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3/dist-packages/setuptools/command/install.py", line 61, in run
        return orig.install.run(self)
      File "/usr/lib/python3.7/distutils/command/install.py", line 589, in run
        self.run_command('build')
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/usr/lib/python3.7/distutils/command/build.py", line 135, in run
        self.run_command(cmd_name)
      File "/usr/lib/python3.7/distutils/cmd.py", line 313, in run_command
        self.distribution.run_command(command)
      File "/usr/lib/python3.7/distutils/dist.py", line 985, in run_command
        cmd_obj.run()
      File "/tmp/pip-req-build-or0bn859/setup.py", line 36, in run
        self.build_extension(ext)
      File "/tmp/pip-req-build-or0bn859/setup.py", line 65, in build_extension
        subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp)
      File "/usr/lib/python3.7/subprocess.py", line 347, in check_call
        raise CalledProcessError(retcode, cmd)
    subprocess.CalledProcessError: Command '['cmake', '/tmp/pip-req-build-or0bn859', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/tmp/pip-req-build-or0bn859/build/lib.linux-x86_64-3.7/', '-DPYTHON_EXECUTABLE=/usr/bin/python3', '-DEXAMPLE_VERSION_INFO=0.1.1', '-DCMAKE_BUILD_TYPE=Release', '-DUSE_PYTHON_EXTENSION=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE', '-DCMAKE_INSTALL_RPATH=$ORIGIN', '-DCMAKE_POSITION_INDEPENDENT_CODE=ON']' returned non-zero exit status 1.
    
    ----------------------------------------
Command "/usr/bin/python3 -u -c "import setuptools, tokenize;__file__='/tmp/pip-req-build-or0bn859/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-8yf5jer6/install-record.txt --single-version-externally-managed --compile --user --prefix=" failed with error code 1 in /tmp/pip-req-build-or0bn859/
```

**Comment by guenhael** [comment]
Hello,

I manually added franka path the PATH variable to fix the previous problem.

I then successfully installed frankx.

Finally, when I run a python script example, I get the following error when importing frankx:

```
Traceback (most recent call last):
  File "read.py", line 14, in <module>
    from frankx import Affine, Robot
  File "/home/username/.local/lib/python3.7/site-packages/frankx/__init__.py", line 3, in <module>
    from _frankx import (
ImportError: libfranka.so.0.8: cannot open shared object file: No such file or directory
```

It is strange because I added /home/username/libfranka/build (where libfranka.so.0.8 is located) to both PATH and PYTHONPATH variables. I also checked the content of sys.path and /home/username/libfranka/build is set properly.

Any suggestion?

**Comment by pantor** [comment]
Hi @guenhael, sorry for the very late response! Frankx did not support libfranka 0.8 so far, but I've merge #24 for 0.8 support just now, so I'll close this. Feel free to open a new issue if new problems arise.
