### ISSUE TITLE
_frankx.NetworkException: libfranka: UDP receive: Timeout

### ISSUE THREAD

**Issue by guenhael** [pantor/frankx#25]
Hello,

I have installed libfranka 0.8.0 and the lattest version of frankx.

When I run a python script, I get the following error:

```
Traceback (most recent call last):
  File "read.py", line 24, in <module>
    robot = Robot(args.host)
  File "/home/user_name/.local/lib/python3.7/site-packages/frankx/robot.py", line 15, in __init__
    super().__init__(fci_ip, dynamic_rel=dynamic_rel, repeat_on_error=repeat_on_error, stop_at_python_signal=stop_at_python_signal)
_frankx.NetworkException: libfranka: UDP receive: Timeout
```

FCI  feature is installed (I have checked on the admin interface) and ping on FCI IP is always bellow 1ms.

Do you have any idea to fix this issue?

Thank you in advance.

**Comment by guenhael** [comment]
Hello,

It was a communication issue that has nothing to do with frankx.

I close this issue.
