### ISSUE TITLE
pip install . not working

### ISSUE THREAD

**Issue by bwunaver** [pantor/frankx#50]
Hi, 

I tried to install from source, using `pip install .`. But it is not working. Here is the error message: 
`
 Preparing metadata (setup.py) ... done
Building wheels for collected packages: frankx
  Building wheel for frankx (setup.py) ... error
  error: subprocess-exited-with-error
  
  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [65 lines of output]
      running bdist_wheel
      running build
      running build_py
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/frankx
      copying frankx/robot.py -> build/lib.linux-x86_64-3.8/frankx
      copying frankx/gripper.py -> build/lib.linux-x86_64-3.8/frankx
      copying frankx/__init__.py -> build/lib.linux-x86_64-3.8/frankx
      running build_ext
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:17 (find_package):
        By not providing "FindFranka.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Franka", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "Franka" (requested
        version 0.8) with any of the following names:
      
          FrankaConfig.cmake
          franka-config.cmake
      
        Add the installation prefix of "Franka" to CMAKE_PREFIX_PATH or set
        "Franka_DIR" to a directory containing one of the above files.  If "Franka"
        provides a separate development package or SDK, be sure it has been
        installed.
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/bwu/original_frankx/frankx/setup.py", line 69, in <module>
          setup(
        File "/home/bwu/original_frankx/original_frankx_env/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/bwu/miniconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/bwu/original_frankx/original_frankx_env/lib/python3.8/site-packages/wheel/bdist_wheel.py", line 343, in run
          self.run_command("build")
        File "/home/bwu/miniconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/bwu/miniconda3/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/bwu/original_frankx/frankx/setup.py", line 36, in run
          self.build_extension(ext)
        File "/home/bwu/original_frankx/frankx/setup.py", line 65, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp)
        File "/home/bwu/miniconda3/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/bwu/original_frankx/frankx', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/bwu/original_frankx/frankx/build/lib.linux-x86_64-3.8/', '-DPYTHON_EXECUTABLE=/home/bwu/original_frankx/original_frankx_env/bin/python3', '-DEXAMPLE_VERSION_INFO=0.2.0', '-DCMAKE_BUILD_TYPE=Release', '-DUSE_PYTHON_EXTENSION=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE', '-DCMAKE_INSTALL_RPATH=$ORIGIN', '-DCMAKE_POSITION_INDEPENDENT_CODE=ON']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for frankx
  Running setup.py clean for frankx
Failed to build frankx
Installing collected packages: frankx
  Running setup.py install for frankx ... error
  error: subprocess-exited-with-error
  
  × Running setup.py install for frankx did not run successfully.
  │ exit code: 1
  ╰─> [67 lines of output]
      running install
      running build
      running build_py
      creating build/lib.linux-x86_64-3.8
      creating build/lib.linux-x86_64-3.8/frankx
      copying frankx/robot.py -> build/lib.linux-x86_64-3.8/frankx
      copying frankx/gripper.py -> build/lib.linux-x86_64-3.8/frankx
      copying frankx/__init__.py -> build/lib.linux-x86_64-3.8/frankx
      running build_ext
      -- The CXX compiler identification is GNU 7.5.0
      -- Detecting CXX compiler ABI info
      -- Detecting CXX compiler ABI info - done
      -- Check for working CXX compiler: /usr/bin/c++ - skipped
      -- Detecting CXX compile features
      -- Detecting CXX compile features - done
      CMake Error at CMakeLists.txt:17 (find_package):
        By not providing "FindFranka.cmake" in CMAKE_MODULE_PATH this project has
        asked CMake to find a package configuration file provided by "Franka", but
        CMake did not find one.
      
        Could not find a package configuration file provided by "Franka" (requested
        version 0.8) with any of the following names:
      
          FrankaConfig.cmake
          franka-config.cmake
      
        Add the installation prefix of "Franka" to CMAKE_PREFIX_PATH or set
        "Franka_DIR" to a directory containing one of the above files.  If "Franka"
        provides a separate development package or SDK, be sure it has been
        installed.
      
      
      -- Configuring incomplete, errors occurred!
      Traceback (most recent call last):
        File "<string>", line 2, in <module>
        File "<pip-setuptools-caller>", line 34, in <module>
        File "/home/bwu/original_frankx/frankx/setup.py", line 69, in <module>
          setup(
        File "/home/bwu/original_frankx/original_frankx_env/lib/python3.8/site-packages/setuptools/__init__.py", line 153, in setup
          return distutils.core.setup(**attrs)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/core.py", line 148, in setup
          dist.run_commands()
        File "/home/bwu/miniconda3/lib/python3.8/distutils/dist.py", line 966, in run_commands
          self.run_command(cmd)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/bwu/original_frankx/original_frankx_env/lib/python3.8/site-packages/setuptools/command/install.py", line 61, in run
          return orig.install.run(self)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/command/install.py", line 545, in run
          self.run_command('build')
        File "/home/bwu/miniconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/bwu/miniconda3/lib/python3.8/distutils/command/build.py", line 135, in run
          self.run_command(cmd_name)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/cmd.py", line 313, in run_command
          self.distribution.run_command(command)
        File "/home/bwu/miniconda3/lib/python3.8/distutils/dist.py", line 985, in run_command
          cmd_obj.run()
        File "/home/bwu/original_frankx/frankx/setup.py", line 36, in run
          self.build_extension(ext)
        File "/home/bwu/original_frankx/frankx/setup.py", line 65, in build_extension
          subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp)
        File "/home/bwu/miniconda3/lib/python3.8/subprocess.py", line 364, in check_call
          raise CalledProcessError(retcode, cmd)
      subprocess.CalledProcessError: Command '['cmake', '/home/bwu/original_frankx/frankx', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/home/bwu/original_frankx/frankx/build/lib.linux-x86_64-3.8/', '-DPYTHON_EXECUTABLE=/home/bwu/original_frankx/original_frankx_env/bin/python3', '-DEXAMPLE_VERSION_INFO=0.2.0', '-DCMAKE_BUILD_TYPE=Release', '-DUSE_PYTHON_EXTENSION=OFF', '-DBUILD_EXAMPLES=OFF', '-DBUILD_TESTS=OFF', '-DBUILD_SHARED_LIBS=OFF', '-DCMAKE_BUILD_WITH_INSTALL_RPATH=TRUE', '-DCMAKE_INSTALL_RPATH=$ORIGIN', '-DCMAKE_POSITION_INDEPENDENT_CODE=ON']' returned non-zero exit status 1.
      [end of output]
  
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> frankx

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.

`

**Comment by bwunaver** [comment]
Hi, 

I found out why it was not working. The path for libfranka was missing. I succeeded to install with: `export LD_LIBRARY_PATH=/home/bwu/libfranka/build:$LD_LIBRARY_PATH`

Thanks!
